# Generated by Django 5.1.3 on 2025-07-07 15:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaracteristiqueEnvoyee",
            fields=[
                (
                    "id_caracteristique_envoyee",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("marque", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("processeur", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=50)),
                ("disque_dur", models.CharField(max_length=50)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                ("id_employe", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "login",
                    models.CharField(
                        blank=True, default="employe.nouveau", max_length=200
                    ),
                ),
                (
                    "mot_de_passe",
                    models.CharField(default="password123", max_length=128),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("telephone", models.CharField(max_length=20, unique=True)),
                ("Département", models.CharField(max_length=191, unique=True)),
                ("date_embauche", models.DateField()),
                ("fonction", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PC",
            fields=[
                ("id_pc", models.AutoField(primary_key=True, serialize=False)),
                ("marque", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("numero_serie", models.CharField(max_length=100, unique=True)),
                ("processeur", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=50)),
                ("disque_dur", models.CharField(max_length=50)),
                ("date_achat", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeDCH",
            fields=[
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="employe_dch",
                        serialize=False,
                        to="Gestionnaire_pc.employe",
                    ),
                ),
                ("DCH_code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeDOT",
            fields=[
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="employe_dot",
                        serialize=False,
                        to="Gestionnaire_pc.employe",
                    ),
                ),
                ("DOT_code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeMGX",
            fields=[
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="employe_mgx",
                        serialize=False,
                        to="Gestionnaire_pc.employe",
                    ),
                ),
                ("MGX_code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeRDAF",
            fields=[
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="employe_rdaf",
                        serialize=False,
                        to="Gestionnaire_pc.employe",
                    ),
                ),
                ("RDAF_code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeRDOT",
            fields=[
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="employe_rdot",
                        serialize=False,
                        to="Gestionnaire_pc.employe",
                    ),
                ),
                ("RDOT_code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeRMG",
            fields=[
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="employe_rmg",
                        serialize=False,
                        to="Gestionnaire_pc.employe",
                    ),
                ),
                ("RMG_code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id_email", models.AutoField(primary_key=True, serialize=False)),
                ("destinataire", models.EmailField(max_length=191)),
                ("objet", models.CharField(max_length=255)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "expediteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to="Gestionnaire_pc.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaracteristiqueRecue",
            fields=[
                (
                    "id_caracteristique_recue",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_recu", models.DateTimeField(auto_now_add=True)),
                (
                    "caracteristique_envoyee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recus",
                        to="Gestionnaire_pc.caracteristiqueenvoyee",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caracteristiques_recues",
                        to="Gestionnaire_pc.employe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="caracteristiqueenvoyee",
            name="employe_concerne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caracteristiques_envoyées",
                to="Gestionnaire_pc.employe",
            ),
        ),
        migrations.AddField(
            model_name="caracteristiqueenvoyee",
            name="envoyeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caracteristiques_envoyees",
                to="Gestionnaire_pc.employe",
            ),
        ),
        migrations.CreateModel(
            name="Pc_ancien",
            fields=[
                ("id_ancien", models.AutoField(primary_key=True, serialize=False)),
                ("date_ajout", models.DateField(auto_now_add=True)),
                (
                    "pc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gestionnaire_pc.pc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pc_attribué",
            fields=[
                ("id_attribue", models.AutoField(primary_key=True, serialize=False)),
                ("marque", models.CharField(default="Marque inconnue", max_length=100)),
                ("modele", models.CharField(default="Modèle inconnu", max_length=100)),
                (
                    "numero_serie",
                    models.CharField(
                        default="Numéro de série inconnu", max_length=100, unique=True
                    ),
                ),
                (
                    "processeur",
                    models.CharField(default="Processeur inconnu", max_length=100),
                ),
                ("ram", models.CharField(default="8 Go", max_length=50)),
                ("disque_dur", models.CharField(default="500 Go", max_length=50)),
                ("date_achat", models.DateField(default=datetime.date.today)),
                ("date_attribution", models.DateField()),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gestionnaire_pc.employe",
                    ),
                ),
            ],
        ),
    ]
