# Generated by Django 5.1.3 on 2025-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="Département",
            field=models.CharField(max_length=191),
        ),
    ]
