# Generated by Django 5.1.3 on 2025-07-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0002_alter_employe_département"),
    ]

    operations = [
        migrations.CreateModel(
            name="marquePC",
            fields=[
                ("id_marque", models.AutoField(primary_key=True, serialize=False)),
                ("nom_marque", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="pc",
            name="marque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pcs",
                to="Gestionnaire_pc.marquepc",
            ),
        ),
        migrations.CreateModel(
            name="modelePC",
            fields=[
                ("id_modele", models.AutoField(primary_key=True, serialize=False)),
                ("nom_modele", models.CharField(max_length=100, unique=True)),
                (
                    "marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modeles",
                        to="Gestionnaire_pc.marquepc",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pc",
            name="modele",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pcs",
                to="Gestionnaire_pc.modelepc",
            ),
        ),
    ]
