# Generated by Django 5.1.3 on 2025-07-08 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0003_marquepc_alter_pc_marque_modelepc_alter_pc_modele"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelepc",
            name="marque",
        ),
    ]
