# Generated by Django 5.1.3 on 2025-07-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0004_remove_modelepc_marque"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="corps",
            field=models.TextField(default="text"),
        ),
    ]
