# Generated by Django 5.1.3 on 2025-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0005_email_corps"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
