# Generated by Django 5.1.3 on 2025-07-10 12:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0006_email_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bordereau",
            fields=[
                ("id_bordereau", models.AutoField(primary_key=True, serialize=False)),
                ("date_creation", models.DateField(default=datetime.date.today)),
                ("nom_employe", models.CharField(max_length=100)),
                ("prenom_employe", models.CharField(max_length=100)),
                ("marque_pc", models.CharField(max_length=100)),
                ("modele_pc", models.CharField(max_length=100)),
                ("numero_serie_pc", models.CharField(max_length=100)),
                ("description_pc", models.TextField()),
                (
                    "telephone_employe",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_employe",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bordereaux_recus",
                        to="Gestionnaire_pc.employe",
                    ),
                ),
            ],
        ),
    ]
