# Generated by Django 5.1.3 on 2025-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0007_bordereau"),
    ]

    operations = [
        migrations.AddField(
            model_name="pc_attribué",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
