# Generated by Django 5.1.3 on 2025-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0008_pc_attribué_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc_attribué",
            name="status",
            field=models.CharField(default="non envoyé", max_length=32),
        ),
    ]
