# Generated by Django 5.1.3 on 2025-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0009_alter_pc_attribué_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bordereau",
            name="date_statut",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bordereau",
            name="statut",
            field=models.CharField(default="non lu", max_length=32),
        ),
    ]
