# Generated by Django 5.1.3 on 2025-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0010_bordereau_date_statut_bordereau_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="pc_attribué",
            name="validation_daf",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pc_attribué",
            name="validation_rmg",
            field=models.BooleanField(default=False),
        ),
    ]
