# Generated by Django 5.1.3 on 2025-07-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestionnaire_pc", "0011_pc_attribué_validation_daf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc_attribué",
            name="validation_daf",
            field=models.CharField(default="en attente", max_length=16),
        ),
        migrations.AlterField(
            model_name="pc_attribué",
            name="validation_rmg",
            field=models.CharField(default="en attente", max_length=16),
        ),
    ]
