# Generated by Django 5.1.4 on 2025-07-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0012_alter_pc_attribué_validation_daf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchatPeripherique',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('materiel', models.CharField(choices=[('Souris', 'Souris'), ('Clavier', 'Clavier'), ('Écran', 'Écran'), ('Imprimante', 'Imprimante'), ('Autre', 'Autre')], max_length=50)),
                ('objet_demande', models.CharField(default="Demande d'achat de périphérique", max_length=255)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('en_cours', 'En cours de traitement'), ('livre', 'Livré')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_achat', to='Gestionnaire_pc.employe')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='Gestionnaire_pc.employe')),
            ],
            options={
                'db_table': 'demande_achat_peripherique',
                'ordering': ['-date_demande'],
            },
        ),
    ]
