# Generated by Django 5.1.4 on 2025-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0013_demandeachatperipherique'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, default='employe@gmail.com', max_length=50),
        ),
    ]
