# Generated by Django 5.1.4 on 2025-07-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0014_employe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='Département',
            field=models.CharField(default='Département inconnu', max_length=191),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(default='Matricule inconnu', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(default='Nom inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(default='Prénom inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(default='0123456789', max_length=20, unique=True),
        ),
    ]
