# Generated by Django 5.1.4 on 2025-07-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0015_alter_employe_département_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(auto_now_add=True),
        ),
    ]
