# Generated by Django 5.1.4 on 2025-07-31 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0017_alter_employe_matricule_alter_employe_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_DAF',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire', models.EmailField(max_length=191)),
                ('objet', models.CharField(max_length=255)),
                ('corps', models.TextField(default='text')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails_daf', to='Gestionnaire_pc.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Email_DCH',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire', models.EmailField(max_length=191)),
                ('objet', models.CharField(max_length=255)),
                ('corps', models.TextField(default='text')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails_dch', to='Gestionnaire_pc.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Email_DOT',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire', models.EmailField(max_length=191)),
                ('objet', models.CharField(max_length=255)),
                ('corps', models.TextField(default='text')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails_dot', to='Gestionnaire_pc.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Email_MGX',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire', models.EmailField(max_length=191)),
                ('objet', models.CharField(max_length=255)),
                ('corps', models.TextField(default='text')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails_mgx', to='Gestionnaire_pc.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Email_RDOT',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire', models.EmailField(max_length=191)),
                ('objet', models.CharField(max_length=255)),
                ('corps', models.TextField(default='text')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails_rdot', to='Gestionnaire_pc.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Email_RMG',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire', models.EmailField(max_length=191)),
                ('objet', models.CharField(max_length=255)),
                ('corps', models.TextField(default='text')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails_rmg', to='Gestionnaire_pc.employe')),
            ],
        ),
    ]
