# Generated by Django 5.1.4 on 2025-08-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0018_email_daf_email_dch_email_dot_email_mgx_email_rdot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc_ancien',
            name='pc',
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='date_achat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='disque_dur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestionnaire_pc.employe'),
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='processeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
