# Generated by Django 5.1.4 on 2025-08-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0019_remove_pc_ancien_pc_pc_ancien_date_achat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc_ancien_attribue',
            fields=[
                ('id_attribue_ancien', models.AutoField(primary_key=True, serialize=False)),
                ('date_attribution', models.DateField()),
                ('date_fin_attribution', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_anciens_attribues', to='Gestionnaire_pc.employe')),
                ('pc_ancien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='Gestionnaire_pc.pc_ancien')),
            ],
        ),
    ]
