# Generated by Django 5.1.4 on 2025-08-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0020_pc_ancien_attribue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc_attribué',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestionnaire_pc.employe', unique=True),
        ),
    ]
