# Generated by Django 5.1.4 on 2025-08-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0021_alter_pc_attribué_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc_attribué',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pc_attribue', to='Gestionnaire_pc.employe'),
        ),
    ]
