# Generated by Django 5.1.4 on 2025-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0022_alter_pc_attribué_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc_ancien_attribue',
            name='pc_ancien',
        ),
        migrations.AddField(
            model_name='pc_ancien_attribue',
            name='date_achat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien_attribue',
            name='disque_dur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien_attribue',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien_attribue',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien_attribue',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien_attribue',
            name='processeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc_ancien_attribue',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
