# Generated by Django 5.1.4 on 2025-08-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0023_remove_pc_ancien_attribue_pc_ancien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauMateriel',
            fields=[
                ('id_materiel', models.AutoField(primary_key=True, serialize=False)),
                ('materiel', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='Gestionnaire_pc.bordereau')),
            ],
        ),
    ]
