# Generated by Django 5.1.4 on 2025-09-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0024_bordereaumateriel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='destinataire',
            field=models.CharField(default='Destinataire inconnu', max_length=100),
        ),
    ]
