# Generated by Django 5.1.4 on 2025-09-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0025_pc_destinataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCaracteristique',
            fields=[
                ('id_caracteristique_recue', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristique', models.TextField(blank=True, default='')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('employe_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_caracteristiques_concernees', to='Gestionnaire_pc.employe')),
                ('envoyeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_caracteristiques_envoyees', to='Gestionnaire_pc.employe')),
            ],
        ),
        migrations.DeleteModel(
            name='CaracteristiqueRecue',
        ),
    ]
