# Generated by Django 5.1.4 on 2025-09-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire_pc', '0026_demandecaracteristique_delete_caracteristiquerecue'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecaracteristique',
            name='statut',
            field=models.CharField(choices=[('non recu', 'non recu'), ('recu', 'recu')], db_index=True, default='non recu', max_length=32),
        ),
    ]
